"""
E5 — Proposition Setup Script
================================
Run ONCE to rebuild ChromaDB and BM25 with proposition-based chunks.

WHAT IT DOES:
1. Loads all 776 parents from data/parent_chunks.json
2. Extracts atomic propositions from each (one LLM call per parent)
3. Clears existing ChromaDB and BM25
4. Indexes all propositions into ChromaDB and BM25
5. Saves BM25 to disk in exact same format as before

WHAT IT DOES NOT TOUCH:
- data/parent_chunks.json  → unchanged (E2 still works perfectly)
- app.py, workflow.py      → unchanged
- All E1 E2 E3 E4 logic    → unchanged

CHECKPOINT SYSTEM:
If the script is interrupted, it saves progress every 50 parents.
Re-running the script automatically resumes from the checkpoint.

RUN:
    python setup_propositions.py

COST : ~$0.155 for 776 parents at gpt-4o-mini rates. One-time only.
TIME : ~10-15 minutes (0.5s delay between API calls for rate limiting)
"""

import os
import sys
import json
import pickle
import shutil
import time
import hashlib
from typing import List
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import page_furniture

from dotenv import load_dotenv
load_dotenv()

from langchain_core.documents import Document
from rank_bm25 import BM25Okapi

import config
from proposition_chunker import PropositionChunker


# ── File paths ────────────────────────────────────────────────────────────────
PARENT_CHUNKS_PATH = "data/parent_chunks.json"
BM25_PATH          = "data/bm25_index.pkl"
CHECKPOINT_PATH    = "data/e5_checkpoint.json"
CACHE_PATH         = "data/proposition_cache.json"


# ── Proposition cache ─────────────────────────────────────────────────────────
# The site is re-scraped every 24 hours, but almost every page comes back byte
# for byte identical. Without a cache each rebuild re-extracts all ~891 parents
# and pays for every one of them again — a recurring bill for an unchanged
# answer.
#
# The cache is keyed on a SHA-1 of the parent's own text, NOT on the parent id.
# Parent ids are regenerated by the scraper and change even when the content
# does not, so keying on them would miss on every run. Content hashing is exact:
# same text in, same key out, and a page that genuinely changed gets a new key
# and is correctly re-extracted.
#
# Only the proposition TEXT is stored. Metadata is rebuilt from the live parent
# on every load (see extract_all_propositions), so a cached entry can never
# carry a stale source, category or parent_id back into the index.
def _fingerprint(content: str) -> str:
    """Content hash of one parent — the cache key."""
    return hashlib.sha1(content.strip().encode("utf-8")).hexdigest()


def load_prop_cache() -> dict:
    """Load the content-keyed proposition cache. Missing file = empty cache."""
    if not os.path.exists(CACHE_PATH):
        return {}
    try:
        with open(CACHE_PATH, "r", encoding="utf-8") as f:
            cache = json.load(f)
        print(f"Proposition cache : {len(cache)} parents cached")
        return cache
    except (json.JSONDecodeError, OSError) as e:
        # A corrupt cache must never break a rebuild — it is an optimisation,
        # not a source of truth. Fall back to extracting everything.
        print(f"WARNING: cache unreadable ({e}). Extracting from scratch.")
        return {}


def save_prop_cache(cache: dict):
    """Persist the cache so the next rebuild — and every daily one — is cheap."""
    os.makedirs("data", exist_ok=True)
    with open(CACHE_PATH, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False)


def seed_cache_from_chromadb() -> dict:
    """Build the cache for free from propositions already in ChromaDB.

    This costs nothing: it is a local read of work already paid for. It must be
    run BEFORE the next scrape, because setup_knowledge_base.py --force clears
    the collection and the existing propositions would be lost.
    """
    import chromadb

    parents_by_id = {p["id"]: p["content"] for p in load_parents()}

    client     = chromadb.PersistentClient(path=config.CHROMA_DB_PATH)
    collection = client.get_collection("university_docs")
    stored     = collection.get(include=["documents", "metadatas"])

    # Group every stored proposition under its parent, preserving prop_index
    # order so the cached list matches the order the extractor produced.
    grouped: dict = {}
    for doc, meta in zip(stored["documents"], stored["metadatas"]):
        meta = meta or {}
        if meta.get("source_type") != "proposition":
            continue
        pid = meta.get("parent_id")
        if not pid:
            continue
        grouped.setdefault(pid, []).append((meta.get("prop_index", 0), doc))

    cache   = {}
    skipped = 0
    for pid, items in grouped.items():
        content = parents_by_id.get(pid)
        if content is None:
            # Parent no longer exists — its propositions are dead weight.
            skipped += 1
            continue
        items.sort(key=lambda pair: pair[0])
        cache[_fingerprint(content)] = [doc for _, doc in items]

    save_prop_cache(cache)
    print(f"\nSeeded {len(cache)} parents into {CACHE_PATH} "
          f"from {len(stored['documents'])} stored propositions.")
    if skipped:
        print(f"  ({skipped} parent_ids in the DB no longer exist — dropped.)")
    print("Cost: $0.00 — this only re-read work already paid for.")
    return cache



# ── Step 1: Load parents ──────────────────────────────────────────────────────
def load_parents() -> list:
    """Load all parent documents from parent_chunks.json."""
    if not os.path.exists(PARENT_CHUNKS_PATH):
        print(f"ERROR: {PARENT_CHUNKS_PATH} not found.")
        print("Run setup_knowledge_base.py first.")
        sys.exit(1)

    with open(PARENT_CHUNKS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Structure: {url_key: {content, metadata}}
    # The key IS the parent_id — not stored inside the value
    parents = []
    refiled = dropped = 0
    for key, val in data.items():
        meta = val.get("metadata", {})
        # PDFs were categorised at scrape time by the page that linked them,
        # which filed every downloads-page policy PDF as "general" and hid it
        # from the policy agent. Re-file from the filename here so the fix
        # reaches the existing corpus on a plain re-run — no re-scrape. Only
        # promotes (-> policy/admissions) or drops procurement noise; never
        # downgrades a PDF a linking page already placed sensibly.
        if meta.get("source_type") == "pdf":
            src     = meta.get("source", key)
            new_cat = config.reclassify_pdf(src, meta.get("category", "general"))
            if new_cat is None:
                dropped += 1
                continue
            if new_cat != meta.get("category"):
                meta = {**meta, "category": new_cat}
                refiled += 1
        parents.append({
            "id"      : key,
            "content" : val.get("content", ""),
            "metadata": meta,
        })

    print(f"Loaded {len(parents)} parents from {PARENT_CHUNKS_PATH}")
    if refiled or dropped:
        print(f"  PDF re-filing: {refiled} promoted to their real agent "
              f"(e.g. policy), {dropped} procurement docs dropped")
    return parents


# ── Step 2: Checkpoint helpers ────────────────────────────────────────────────
def load_checkpoint() -> dict:
    """Load progress so interrupted runs can resume."""
    if os.path.exists(CHECKPOINT_PATH):
        with open(CHECKPOINT_PATH, "r", encoding="utf-8") as f:
            ckpt = json.load(f)
        print(f"Checkpoint found: {ckpt['processed']} parents already done, "
              f"{len(ckpt['propositions'])} propositions collected.")
        return ckpt
    return {"processed": 0, "propositions": []}


def save_checkpoint(processed: int, propositions: List[Document]):
    """Save progress checkpoint."""
    os.makedirs("data", exist_ok=True)
    prop_data = [
        {"content": p.page_content, "metadata": p.metadata}
        for p in propositions
    ]
    with open(CHECKPOINT_PATH, "w", encoding="utf-8") as f:
        json.dump({"processed": processed, "propositions": prop_data}, f)


def docs_from_checkpoint(raw: list) -> List[Document]:
    """Rebuild Document objects from checkpoint data."""
    return [
        Document(page_content=p["content"], metadata=p["metadata"])
        for p in raw
    ]


# ── Step 3: Extract propositions ──────────────────────────────────────────────
def extract_all_propositions(
    parents    : list,
    start_from : int,
    existing   : List[Document],
) -> List[Document]:
    """Run proposition extraction on all parents with checkpointing."""

    chunker           = PropositionChunker(model="gpt-4o-mini", batch_delay=0.5)
    all_propositions  = list(existing)
    parents_remaining = parents[start_from:]
    total             = len(parents)
    CHECKPOINT_EVERY  = 50

    cache        = load_prop_cache()
    cache_hits   = 0
    cache_misses = 0

    # Count hits up front so the cost estimate below is the real number, not the
    # worst case. Only misses cost money.
    to_extract = sum(1 for p in parents_remaining
                     if _fingerprint(p.get("content", "")) not in cache)

    print(f"\nExtracting propositions from {len(parents_remaining)} parents...")
    print(f"  cached (free) : {len(parents_remaining) - to_extract}")
    print(f"  to extract    : {to_extract}")
    print(f"Estimated time : ~{to_extract * 0.5 / 60:.1f} minutes")
    print(f"Estimated cost : ~${to_extract * 0.0002:.3f}\n")

    for i, parent in enumerate(parents_remaining):
        parent_id      = parent.get("id", f"parent_{start_from + i}")
        parent_content = parent.get("content", "")
        parent_meta    = parent.get("metadata", {})

        fingerprint = _fingerprint(parent_content)
        cached      = cache.get(fingerprint)

        if cached is not None:
            # Rebuild the Documents from the live parent's metadata so a cached
            # entry can never reintroduce a stale parent_id or source. This
            # mirrors exactly what PropositionChunker.extract_propositions
            # builds, so cached and freshly-extracted rows are indistinguishable
            # downstream.
            props = [
                Document(
                    page_content = text,
                    metadata     = {
                        **parent_meta,
                        "parent_id"   : parent_id,
                        "source_type" : "proposition",
                        "prop_index"  : j,
                    },
                )
                for j, text in enumerate(cached)
            ]
            cache_hits += 1
        else:
            props = chunker.extract_propositions(
                parent_content  = parent_content,
                parent_metadata = parent_meta,
                parent_id       = parent_id,
            )
            cache[fingerprint] = [p.page_content for p in props]
            cache_misses += 1

        all_propositions.extend(props)

        processed = start_from + i + 1

        # Print progress every 10 parents
        if processed % 10 == 0 or processed == total:
            print(f"  [{processed}/{total}] "
                  f"{len(all_propositions)} propositions total "
                  f"(cached {cache_hits}, extracted {cache_misses})")

        # Save checkpoint every 50 parents
        if processed % CHECKPOINT_EVERY == 0:
            save_checkpoint(processed, all_propositions)
            save_prop_cache(cache)
            print(f"  [Checkpoint saved at {processed} parents]")

        # Rate limiting — stay within API limits. A cache hit made no API call,
        # so sleeping after one would waste wall-clock for nothing. This is what
        # turns a full unchanged rebuild from ~10 minutes into seconds.
        if cached is None and i < len(parents_remaining) - 1:
            time.sleep(0.5)

    save_prop_cache(cache)
    print(f"\nExtraction complete: {len(all_propositions)} total propositions")
    print(f"  served from cache : {cache_hits} parents ($0.00)")
    print(f"  extracted via API : {cache_misses} parents "
          f"(~${cache_misses * 0.0002:.3f})")
    return all_propositions


# ── Step 3b: Drop redundant propositions ──────────────────────────────────────
def drop_redundant(propositions: List[Document]) -> List[Document]:
    """Remove propositions that repeat a sentence already stored in their category.

    Runs BEFORE rebuild_chromadb and rebuild_bm25, for three reasons:

      * both of those take the same list, so deduping once here keeps the two
        stores in sync by construction — there is no second place to forget.
      * nothing has been embedded yet, so every row removed here is a row we do
        not pay to embed.
      * it is the only point where the whole corpus is in hand. The extractor
        works one parent at a time and cannot know that the sentence it just
        wrote about the university's address is the 54th copy.

    Measured on the current corpus: 629 of 5486 propositions (11.5%) are
    redundant under the (text, category) rule with the last-child guard. The rule
    itself lives in page_furniture.find_redundant, shared with
    repair_duplicate_children.py so the rebuild and the repair cannot disagree
    about what counts as a duplicate.
    """
    rows = [
        (i, d.page_content,
         (d.metadata or {}).get("category", ""),
         (d.metadata or {}).get("parent_id"))
        for i, d in enumerate(propositions)
    ]
    drop = set(page_furniture.find_redundant(rows))
    if not drop:
        print("\nNo redundant propositions found.")
        return propositions

    kept = [d for i, d in enumerate(propositions) if i not in drop]
    print(f"\nRedundant propositions dropped : {len(drop)} "
          f"({len(drop) / max(len(propositions), 1):.1%})")
    print(f"  before : {len(propositions)}")
    print(f"  after  : {len(kept)}")
    print(f"  (one copy kept per category, and never a parent's last child)")
    return kept


# ── Step 4: Rebuild ChromaDB ──────────────────────────────────────────────────
def rebuild_chromadb(propositions: List[Document]):
    """Delete old ChromaDB and index all propositions fresh."""

    print(f"\nRebuilding ChromaDB with {len(propositions)} propositions...")

    # Delete old ChromaDB directory completely
    chroma_path = config.CHROMA_DB_PATH
    if os.path.exists(chroma_path):
        shutil.rmtree(chroma_path)
        print(f"Old ChromaDB deleted: {chroma_path}")

    # Import same way knowledge_base.py does
    try:
        from langchain_chroma import Chroma
    except ImportError:
        from langchain_community.vectorstores import Chroma

    try:
        from langchain_openai import OpenAIEmbeddings
    except ImportError:
        from langchain_community.embeddings import OpenAIEmbeddings

    embeddings = OpenAIEmbeddings(
        model          = config.EMBEDDING_MODEL,
        openai_api_key = config.OPENAI_API_KEY,
    )

    db = Chroma(
        collection_name    = config.CHROMA_COLLECTION,
        embedding_function = embeddings,
        persist_directory  = chroma_path,
    )

    # Add in batches to avoid memory issues
    batch_size = 100
    total      = len(propositions)

    for i in range(0, total, batch_size):
        batch = propositions[i : i + batch_size]
        db.add_documents(batch)
        print(f"  ChromaDB: {min(i + batch_size, total)}/{total} indexed")

    print(f"ChromaDB rebuilt: {total} proposition chunks.")
    return db


# ── Step 5: Rebuild BM25 ──────────────────────────────────────────────────────
def rebuild_bm25(propositions: List[Document]):
    """Rebuild BM25 index in exact same format as knowledge_base.py."""

    print(f"\nRebuilding BM25 with {len(propositions)} propositions...")

    corpus = [doc.page_content.lower().split() for doc in propositions]
    bm25   = BM25Okapi(corpus)

    # Save in exact format that _load_bm25_from_disk expects
    os.makedirs("./data", exist_ok=True)
    with open(BM25_PATH, "wb") as f:
        pickle.dump({"bm25": bm25, "docs": propositions}, f)

    print(f"BM25 rebuilt and saved: {len(propositions)} documents.")


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("  E5 — Proposition-Based Chunking Setup")
    print("=" * 60)

    # Load parents
    parents = load_parents()

    # Load checkpoint — resume if interrupted
    ckpt       = load_checkpoint()
    start_from = ckpt["processed"]
    existing   = docs_from_checkpoint(ckpt["propositions"])

    # Extract propositions
    all_propositions = extract_all_propositions(
        parents    = parents,
        start_from = start_from,
        existing   = existing,
    )

    # Drop redundant copies before either store is built, and before anything is
    # embedded. Both rebuilds below take this same list, so one call here is what
    # keeps ChromaDB and BM25 holding identical rows.
    all_propositions = drop_redundant(all_propositions)

    # Rebuild ChromaDB
    rebuild_chromadb(all_propositions)

    # Rebuild BM25
    rebuild_bm25(all_propositions)

    # Clean up checkpoint
    if os.path.exists(CHECKPOINT_PATH):
        os.remove(CHECKPOINT_PATH)

    print("\n" + "=" * 60)
    print(f"  E5 Setup Complete!")
    print(f"  Propositions : {len(all_propositions)}")
    print(f"  Parents      : {len(parents)} (unchanged — E2 still works)")
    print(f"  Run app.py to test the improved system.")
    print("=" * 60)


if __name__ == "__main__":
    # --seed-cache fills data/proposition_cache.json from the propositions
    # already sitting in ChromaDB, then exits without extracting anything.
    # Run it BEFORE a re-scrape: setup_knowledge_base.py --force clears the
    # collection, and once it is gone that free seed is gone with it.
    if "--seed-cache" in sys.argv:
        seed_cache_from_chromadb()
    else:
        main()